#pragma config(Motor,  motorB,          LeftMotor,     tmotorNXT, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          RightMotor,    tmotorNXT, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//                  Synchronized Motor Examples

// This program example uses synchronized motors, feedback from encoders and the nMotorEncoderTarget function

task main()
{
	nSyncedMotors = synchBC; //motor B is the master, motor C is the slave
	nSyncedTurnRatio = 100; //motors move at i% alignment to each other

	nMotorEncoder[motorB] = 0; //reset the value of motorB's encoder to zero

	nMotorEncoderTarget[motorB] = 360*8; //set motorB's target position to 720

	motor[motorB] = 30; //power motorB at 30% power
	wait1Msec(4000);

	while(nMotorRunState[motorB] != runStateIdle)//while motorB is not in an idle position
	{
		for (int i=50; i>-101; i-=50)
		{

			nSyncedMotors = synchBC; //motor B is the master, motor C is the slave
			nSyncedTurnRatio = i; //motors move at i% alignment to each other
			//nMotorEncoder[motorB] = 0; //reset the value of motorB's encoder to zero
			motor[motorB] = 30; //power motorB at 30% power
			wait1Msec(4000);

			//continue to monitor nMotorEncoderTarget's target position
		}
	}
	motor[motorB] = 0;  // turn the motors off.

	wait1Msec(8000);
}
