#pragma config(Sensor, S1,     PIXYC,          sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "pixyCamV1-lib-RK1b.h"


 task main()
{

	//bool bFastI2C=true;
  short _sigVal=0;
  ubyte _xPos=0;
  ubyte _yPos=0;
  ubyte _width=0;
  ubyte _height=0;
  ubyte _angle=0;

	initializeI2CSensor(PIXYC, false);
	sleep(150);

	while (true)
	{
		eraseDisplay();

	  while (!PIXYCreadGeneralQry(PIXYC, _sigVal, _xPos, _yPos, _width, _height))
			{
				//wait for read to return bool 'true'
				sleep(50);
			}

			while (!PIXYCreadAngleQry(PIXYC, _angle))
			{
				//wait for read to return bool 'true'
				sleep(50);
			}

			displayTextLine(1, "sigVal: %d", _sigVal);
			displayTextLine(2, "xPos: %d", _xPos);
			displayTextLine(3, "yPos: %d", _yPos);
			displayTextLine(4, "width: %d", _width);
			displayTextLine(5, "height: %d", _height);
			displayTextLine(6, "angle: %d", _angle);

			sleep(100);

		}
}
