#pragma config(Sensor, S1,     PIXYC,          sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "pixyCamV1-lib-RK1a.h"


 task main()
{

	//bool bFastI2C=true;

  ubyte qryAddress = 0x51;   // The address of the Signature (51-57)

	initializeI2CSensor(PIXYC, false);
	sleep(150);

	while (true)
	{
		eraseDisplay();

	  while (!PIXYCreadSignatureQry(PIXYC, qryAddress))
			{
				//wait for read to return bool 'true'
				sleep(50);
			}

			displayTextLine(1, "numberOfBlocks: %d", numberOfBlocks);
			displayTextLine(2, "xPos: %d", xPos);
			displayTextLine(3, "yPos: %d", yPos);
			displayTextLine(4, "width: %d", width);
			displayTextLine(5, "height: %d", height);

			sleep(100);

		}
}
