#pragma config(Sensor, S1,     MICC,           sensorI2CCustom)
#pragma config(Sensor, S2,     HTcompass,      sensorI2CHiTechnicCompass)
#pragma config(Sensor, S3,     HTgyro,         sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorB,          LeftMotor,     tmotorNXT, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          RightMotor,    tmotorNXT, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
* microinfinity-cruizcore.h provides an API for the MicroInfinity CruizCore XG1300L sensor.
*/

#include "microinfinity-cruizcore.h"

/**
int rangeLim(int val, int lim) //(abs(val+lim)-abs(val-lim))/2 ...returns vals in range of +/- lim
{
val = (abs(val+lim)-abs(val-lim))/2;
return val;
}
*/

int rangeLim(int val, int lim) //((abs(val)-abs(val-lim))/2)+lim/2 ...returns vals in range of 0-> lim
{
	val = ((abs(val)-abs(val-lim))/2)+lim/2;
	return val;
}

task main ()
{
	short angleI = 0;
	float angleF = 0.0;
	float errF = 0.0;
	float errFsum = 0.0;
	int pwr = 85;
	int c = 10;  //min motor pwr
	pwr=rangeLim(pwr,90);
	float minF = 0.0;
	float maxF = 0.0;

	for (int i=0; i<100; i++)
	{
		writeDebugStreamLine("For loop (nPgmTime,pwr,i), %d, %d, %d", nPgmTime,pwr,i);
		wait1Msec(1);
		pwr--;
		pwr=rangeLim(pwr,60);
		motor[LeftMotor]=pwr+c; // set motor pwr with var + min motor setting of c
		wait1Msec(100);

	}
	writeDebugStreamLine("End (nPgmTime,pwr), %d, %d", nPgmTime,pwr);

}
