#pragma config(Sensor, S2,     touchA,         sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
* This program will test the ability to track an input value (encoder from MotorB)
* and have MotorA move according to that input using PID, rangeLim, and scaling.
*
* Additional features:
* - set the initial MotorA encoder, using a touch sensor as a limit switch.
* - set the min and max MotorA encoder values as motion limits
*/

task main()
{
	// initialize vars and motor encoder values
	int motorApwr;
	int encoderAdeg=0;
	int encoderBdeg=0;

	nMotorEncoder[motorA]=0;
	nMotorEncoder[motorB]=0;

	// initialize MotorA encoder, using a touch sensor as a limit switch; then center in range
	while (!SensorValue[touchA])
	{
		motor[motorA]=5;
	}

	playSound(soundBlip);
	nMotorEncoder[motorA]=0;
	wait1Msec(500);

	nMotorEncoderTarget[motorA] = 103;
	motor[motorA] = -13;

	while(nMotorRunState[motorA] != runStateIdle)  // while Motor A is still running:
	{
		// do nothing
	}
	motor[motorA] = 0;

	nMotorEncoder[motorA]=0;
	nMotorEncoder[motorB]=0;


	// MotorA follows MotorB
	while (abs(nMotorEncoder[motorA]) <= 80) {
		motorApwr=nMotorEncoder[motorB] - nMotorEncoder[motorA];
		motor[motorA] = motorApwr;
		encoderAdeg = nMotorEncoder[motorA];
		encoderBdeg = nMotorEncoder[motorB];
		if (SensorValue[touchA]) playSound(soundBlip);
		eraseDisplay();
		displayTextLine(1, "encoderAdeg: %d", encoderAdeg);
		displayTextLine(2, "encoderBdeg: %d", encoderBdeg);
		displayTextLine(3, "motorApwr: %d", motorApwr);
		displayTextLine(6, "RunState(hex):%x", nMotorRunState[motorA]);
		wait1Msec(50);

	} // while end

	motor[motorA] = 0;
	encoderAdeg = nMotorEncoder[motorA];
	encoderBdeg = nMotorEncoder[motorB];
	eraseDisplay();
	displayTextLine(1, "encoderAdeg: %d", encoderAdeg);
	displayTextLine(2, "encoderBdeg: %d", encoderBdeg);
	displayTextLine(3, "motorApwr: %d", motorApwr);
	displayTextLine(6, "RunState(hex):%x", nMotorRunState[motorA]);

	while(true) {
		playSound(soundBeepBeep);
		wait1Msec(3000);
	} // while end


}
