#pragma config(Sensor, S1,     PIXYC,          sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "pixyCamV1-lib-RK1a.h"


 task main()
{

	//bool bFastI2C=true;
  int pwr=0;

	initializeI2CSensor(PIXYC, false);
	sleep(150);

	while (true)
	{
		eraseDisplay();

	  while (!PIXYCreadGeneralQry(PIXYC))
			{
				//wait for read to return bool 'true'
				sleep(50);
			}

			displayTextLine(1, "sigVal: %d", sigVal);
			displayTextLine(2, "xPos: %d", xPos);
			displayTextLine(3, "yPos: %d", yPos);
			displayTextLine(4, "width: %d", width);
			displayTextLine(5, "height: %d", height);

			if (xPos>0 && xPos<200) playImmediateTone(440, 1200);

			sleep(100);

		nMotorEncoder[motorA]=0; //reset encoder

		for(int i=0;i<1500;i++) //iterate for 3000 ms
		{
			pwr=i/40;
			motor[motorA] = pwr;  //motor speed will ramp up to approx 37
			wait1Msec(2);  //run the motor for 3 secs
		}

		for(int i=1500;i>0;i--) //iterate for 3000 ms
		{
			pwr=i/40;
			motor[motorA] = pwr;  //motor speed will ramp down from 37 to 0
			wait1Msec(2);  //run the motor for 3 secs
		}
		motor[motorA] = 0; //motor will not ramp 'down' but will coast to stop

		sleep(15000);

		}
}
