#pragma config(Sensor, S1,     MICC,           sensorI2CCustom)
#pragma config(Sensor, S2,     HTcompass,      sensorI2CHiTechnicCompass)
#pragma config(Sensor, S3,     HTgyro,         sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorB,          LeftMotor,     tmotorNXT, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          RoghtMotor,    tmotorNXT, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

///////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                             Hello World
//
// This is the 'classic' "Hello World" program. Text is drawn on the NXT LCD
//
///////////////////////////////////////////////////////////////////////////////////////////////////////

{
	displayTextLine(4, "   Hello World  ");  // Display the text on line number 4 of 8 on the LCD
	wait1Msec(5000);														// Wait a bit otherwise program will finish and text not visible
}
