#pragma config(Sensor, S1,     touchSensor,    sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	while(true)
	{
		while(SensorValue(touchSensor) == 0)   //a while loop is declared with the touchsensor's value being 0 as it true condition
		{
			displayBigTextLine(4, "%d", SensorValue(touchSensor));
			wait1Msec(500);
		}

		displayBigTextLine(4, "%d", SensorValue(touchSensor));
		wait1Msec(500);
	}

}
