#pragma config(Motor,  motorB,          LeftMotor,     tmotorNXT, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          RightMotor,    tmotorNXT, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//                  Synchronized Motors for steering control

task main()
{
	wait1Msec(2000);  // wait for 2000mS
	//startTask(DisplayAndButtons);
	int TrnRatio=100;
	int syncErr=0;
	nMotorEncoder[LeftMotor]=0;
	nMotorEncoder[RightMotor]=0;
	wait1Msec(1);
	nSyncedMotors = synchBC; //motor B is the master, motor C is the slave
	wait1Msec(1);

	while(true)
	{
		eraseDisplay();

		switch(nNxtButtonPressed)
		{
		case kLeftButton:
			{
				eraseDisplay();
				displayCenteredBigTextLine(4, "Left");
				TrnRatio-=25;
				nSyncedMotors = synchBC; //motor B is the master, motor C is the slave
				break;
			}
		case kEnterButton:
			{
				eraseDisplay();
				displayCenteredBigTextLine(4, "Enter");
				TrnRatio=100;
				nSyncedMotors = synchBC; //motor B is the master, motor C is the slave
				displayCenteredTextLine(6, "TrnRatio  %d", TrnRatio);
				break;
			}
		case kRightButton:
			{
				eraseDisplay();
				displayCenteredBigTextLine(4, "Right");
				TrnRatio+=25;
				nSyncedMotors = synchBC; //motor B is the master, motor C is the slave
				break;
			}
		case kExitButton:
			{
				eraseDisplay();
				displayCenteredBigTextLine(4, "Exit");
				motor[motorB] = 0;  // turn the motors off.
				wait1Msec(8000);  // wait for 8000mS
				break;
			}
		case -1:
			{
				displayCenteredBigTextLine(4, "None");
				break;
			}
		}
		displayCenteredTextLine(1, "LeftMotor %d",nMotorEncoder[LeftMotor]);
		displayCenteredTextLine(2, "RightMotor %d",nMotorEncoder[RightMotor]);
		//displayCenteredTextLine(6, "TrnRatio  %d", TrnRatio);
		if (abs(nMotorEncoder[LeftMotor]-nMotorEncoder[RightMotor])>50)
		{
			syncErr++;
			displayCenteredBigTextLine(4, "syncErr");
			displayCenteredTextLine(7, "%d",syncErr);
			wait1Msec(200);
		}

		nSyncedTurnRatio = TrnRatio; //sets turn ratio

		motor[motorB] = 30; //turn motor B on, which controls motor C at 30% power
		displayCenteredTextLine(6, "TrnRatio  %d", TrnRatio);
		wait1Msec(150);  // wait for 150mS
	}

}
